#############################################################################
# Makefile for building: Neuropia.js
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  Neuropia.pro
# Template: app
# Command: /opt/Qt/5.13.0/wasm_32/bin/qmake -o Makefile Neuropia.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = emcc
CXX           = em++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -Oz -s ALLOW_MEMORY_GROWTH=1 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -Wno-multichar -O3 -Oz -std=gnu++1y -s ALLOW_MEMORY_GROWTH=1 -Wall -W $(DEFINES)
INCPATH       = -I. -Iinclude -I/opt/Qt/5.13.0/wasm_32/include -I/opt/Qt/5.13.0/wasm_32/include/QtCore -I. -I/home/markus/.emscripten_ports/openssl/include -I/opt/Qt/5.13.0/wasm_32/mkspecs/wasm-emscripten
QMAKE         = /opt/Qt/5.13.0/wasm_32/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/Qt/5.13.0/wasm_32/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/Qt/5.13.0/wasm_32/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Neuropia.js1.0.0
DISTDIR = /home/markus/Development/Neuropia/.tmp/Neuropia.js1.0.0
LINK          = em++
LFLAGS        = -s WASM=1 -s FULL_ES2=1 -s USE_WEBGL2=1 -s NO_EXIT_RUNTIME=0 -s ERROR_ON_UNDEFINED_SYMBOLS=1 --bind -s "BINARYEN_TRAP_MODE='clamp'" -O3 -s ALLOW_MEMORY_GROWTH=1
LIBS          = $(SUBLIBS) /opt/Qt/5.13.0/wasm_32/lib/libQt5Core.a /opt/Qt/5.13.0/wasm_32/lib/libqtpcre2.a   
AR            = emar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/neuropia.cpp \
		src/idxreader.cpp \
		src/neuropia_simple.cpp \
		src/utils.cpp \
		src/testports.cpp \
		src/params.cpp \
		src/trainer.cpp \
		src/verify.cpp \
		src/paralleltrain.cpp \
		src/evotrain.cpp \
		src/argparse.cpp \
		src/trainerbase.cpp 
OBJECTS       = main.o \
		neuropia.o \
		idxreader.o \
		neuropia_simple.o \
		utils.o \
		testports.o \
		params.o \
		trainer.o \
		verify.o \
		paralleltrain.o \
		evotrain.o \
		argparse.o \
		trainerbase.o
DIST          = tests/tests.txt \
		tests/tests2.txt \
		tests/tests3.txt \
		tests/tests5.txt \
		tests/tests4.txt \
		tests/tests7.txt \
		tests/tests8.txt \
		tests/tests9.txt \
		tests/tests10.txt \
		tests/tests11.txt \
		tests/tests12.txt \
		tests/tests13.txt \
		tests/tests14.txt \
		tests/tests15.txt \
		tests/tests16.txt \
		tests/tests17.txt \
		tests/tests18.txt \
		tests/tests20.txt \
		tests/tests21.txt \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/common/sanitize.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/common/clang.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/qdevice.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/device_config.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/qconfig.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt_config.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/spec_post.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/toolchain.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/default_pre.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/default_post.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/wasm/wasm.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/warn_on.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/resources.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/moc.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/file_copies.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/exceptions.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/yacc.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/lex.prf \
		Neuropia.pro include/neuropia.h \
		include/idxreader.h \
		include/matrix.h \
		include/neuropia_simple.h \
		include/paralleltrain.h \
		include/utils.h \
		include/evotrain.h \
		include/verify.h \
		include/params.h \
		include/trainer.h \
		include/argparse.h \
		include/trainerbase.h src/main.cpp \
		src/neuropia.cpp \
		src/idxreader.cpp \
		src/neuropia_simple.cpp \
		src/utils.cpp \
		src/testports.cpp \
		src/params.cpp \
		src/trainer.cpp \
		src/verify.cpp \
		src/paralleltrain.cpp \
		src/evotrain.cpp \
		src/argparse.cpp \
		src/trainerbase.cpp
QMAKE_TARGET  = Neuropia.js
DESTDIR       = 
TARGET        = Neuropia.js


first: all
####### Build rules

Neuropia.js: /opt/Qt/5.13.0/wasm_32/lib/libQt5Core.a $(OBJECTS)  apphtml appjs appsvg
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Neuropia.pro /opt/Qt/5.13.0/wasm_32/mkspecs/wasm-emscripten/qmake.conf /opt/Qt/5.13.0/wasm_32/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/common/sanitize.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/common/clang.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/qdevice.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/device_config.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/qconfig.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qgif.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qicns.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qico.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtga.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt_config.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/wasm-emscripten/qmake.conf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/spec_post.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/toolchain.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/default_pre.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/default_post.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/wasm/wasm.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/warn_on.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/resources.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/moc.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/file_copies.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/exceptions.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/yacc.prf \
		/opt/Qt/5.13.0/wasm_32/mkspecs/features/lex.prf \
		Neuropia.pro \
		/opt/Qt/5.13.0/wasm_32/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Neuropia.pro
/opt/Qt/5.13.0/wasm_32/mkspecs/features/spec_pre.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/common/sanitize.conf:
/opt/Qt/5.13.0/wasm_32/mkspecs/common/gcc-base.conf:
/opt/Qt/5.13.0/wasm_32/mkspecs/common/clang.conf:
/opt/Qt/5.13.0/wasm_32/mkspecs/qdevice.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/device_config.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/qconfig.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_repparser.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_eglvideonode.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qgif.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qicns.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qico.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qjpeg.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qminimal.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qoffscreen.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qsvg.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qsvgicon.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtga.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtiff.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qvnc.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwasm.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwbmp.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/modules/qt_plugin_qwebp.pri:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt_functions.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt_config.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/wasm-emscripten/qmake.conf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/spec_post.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/toolchain.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/default_pre.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/resolve_config.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/default_post.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/wasm/wasm.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/warn_on.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/qt.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/resources.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/moc.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/qmake_use.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/file_copies.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/exceptions.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/yacc.prf:
/opt/Qt/5.13.0/wasm_32/mkspecs/features/lex.prf:
Neuropia.pro:
/opt/Qt/5.13.0/wasm_32/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Neuropia.pro

qmake_all: FORCE


all: Makefile Neuropia.js

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt/5.13.0/wasm_32/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/neuropia.h include/idxreader.h include/matrix.h include/neuropia_simple.h include/paralleltrain.h include/utils.h include/evotrain.h include/verify.h include/params.h include/trainer.h include/argparse.h include/trainerbase.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/neuropia.cpp src/idxreader.cpp src/neuropia_simple.cpp src/utils.cpp src/testports.cpp src/params.cpp src/trainer.cpp src/verify.cpp src/paralleltrain.cpp src/evotrain.cpp src/argparse.cpp src/trainerbase.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) *.html *.js *.wasm .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

apphtml: /opt/Qt/5.13.0/wasm_32/plugins/platforms/wasm_shell.html
	sed -e s/APPNAME/Neuropia/g /opt/Qt/5.13.0/wasm_32/plugins/platforms/wasm_shell.html > /home/markus/Development/Neuropia/Neuropia.html

appjs: /opt/Qt/5.13.0/wasm_32/plugins/platforms/qtloader.js
	cp -f /opt/Qt/5.13.0/wasm_32/plugins/platforms/qtloader.js /home/markus/Development/Neuropia

appsvg: /opt/Qt/5.13.0/wasm_32/plugins/platforms/qtlogo.svg
	cp -f /opt/Qt/5.13.0/wasm_32/plugins/platforms/qtlogo.svg /home/markus/Development/Neuropia

shellfiles: apphtml appjs appsvg

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_apphtml_make_all:
compiler_apphtml_clean:
	-$(DEL_FILE) Neuropia.html
compiler_appjs_make_all:
compiler_appjs_clean:
	-$(DEL_FILE) qtloader.js
compiler_appsvg_make_all:
compiler_appsvg_clean:
	-$(DEL_FILE) qtlogo.svg
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt/5.13.0/wasm_32/mkspecs/features/data/dummy.cpp
	em++ -pipe -Wno-multichar -O3 -Oz -std=gnu++1y -s ALLOW_MEMORY_GROWTH=1 -Wall -W -dM -E -o moc_predefs.h /opt/Qt/5.13.0/wasm_32/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: src/main.cpp include/neuropia.h \
		include/trainer.h \
		include/trainerbase.h \
		include/idxreader.h \
		include/paralleltrain.h \
		include/utils.h \
		include/evotrain.h \
		include/verify.h \
		include/params.h \
		include/argparse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

neuropia.o: src/neuropia.cpp include/neuropia.h \
		include/matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuropia.o src/neuropia.cpp

idxreader.o: src/idxreader.cpp include/idxreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o idxreader.o src/idxreader.cpp

neuropia_simple.o: src/neuropia_simple.cpp include/neuropia_simple.h \
		include/params.h \
		include/evotrain.h \
		include/neuropia.h \
		include/idxreader.h \
		include/utils.h \
		include/trainerbase.h \
		include/trainer.h \
		include/paralleltrain.h \
		include/verify.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o neuropia_simple.o src/neuropia_simple.cpp

utils.o: src/utils.cpp include/neuropia.h \
		include/utils.h \
		include/matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/utils.cpp

testports.o: src/testports.cpp include/neuropia.h \
		include/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testports.o src/testports.cpp

params.o: src/params.cpp include/params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o params.o src/params.cpp

trainer.o: src/trainer.cpp include/trainer.h \
		include/trainerbase.h \
		include/neuropia.h \
		include/idxreader.h \
		include/verify.h \
		include/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trainer.o src/trainer.cpp

verify.o: src/verify.cpp include/verify.h \
		include/neuropia.h \
		include/idxreader.h \
		include/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o verify.o src/verify.cpp

paralleltrain.o: src/paralleltrain.cpp include/utils.h \
		include/paralleltrain.h \
		include/trainerbase.h \
		include/neuropia.h \
		include/idxreader.h \
		include/params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paralleltrain.o src/paralleltrain.cpp

evotrain.o: src/evotrain.cpp include/evotrain.h \
		include/neuropia.h \
		include/idxreader.h \
		include/utils.h \
		include/trainerbase.h \
		include/params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o evotrain.o src/evotrain.cpp

argparse.o: src/argparse.cpp include/argparse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o argparse.o src/argparse.cpp

trainerbase.o: src/trainerbase.cpp include/trainerbase.h \
		include/neuropia.h \
		include/idxreader.h \
		include/utils.h \
		include/params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trainerbase.o src/trainerbase.cpp

####### Install

install_js_file: first FORCE
	@test -d $(INSTALL_ROOT)/home/markus/Development/Neuropia/./ || mkdir -p $(INSTALL_ROOT)/home/markus/Development/Neuropia/./
	-$(QINSTALL_PROGRAM) /home/markus/Development/Neuropia/Neuropia.js $(INSTALL_ROOT)/home/markus/Development/Neuropia/./Neuropia.js

uninstall_js_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/markus/Development/Neuropia/./Neuropia.js
	-$(DEL_DIR) $(INSTALL_ROOT)/home/markus/Development/Neuropia/./ 


install: install_js_file  FORCE

uninstall: uninstall_js_file  FORCE

FORCE:

